import type { AbiFunctionConfig } from '../types';

const textResult = (name: string) => [{ name, type: 'string' }];
const numberResult = (name: string) => [{ name, type: 'uint256' }];
const boolResult = (name: string) => [{ name, type: 'bool' }];
const addressResult = (name: string) => [{ name, type: 'address' }];

export const erc20Functions: AbiFunctionConfig[] = [
  {
    label: 'name()',
    signature: 'name()',
    methodName: 'name',
    stateMutability: 'view',
    inputs: [],
    outputs: textResult('name'),
    abi: {
      type: 'function',
      name: 'name',
      stateMutability: 'view',
      inputs: [],
      outputs: [{ name: 'name', type: 'string' }],
    },
  },
  {
    label: 'symbol()',
    signature: 'symbol()',
    methodName: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: textResult('symbol'),
    abi: {
      type: 'function',
      name: 'symbol',
      stateMutability: 'view',
      inputs: [],
      outputs: [{ name: 'symbol', type: 'string' }],
    },
  },
  {
    label: 'decimals()',
    signature: 'decimals()',
    methodName: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: numberResult('decimals'),
    abi: {
      type: 'function',
      name: 'decimals',
      stateMutability: 'view',
      inputs: [],
      outputs: [{ name: 'decimals', type: 'uint8' }],
    },
  },
  {
    label: 'totalSupply()',
    signature: 'totalSupply()',
    methodName: 'totalSupply',
    stateMutability: 'view',
    inputs: [],
    outputs: numberResult('totalSupply'),
    abi: {
      type: 'function',
      name: 'totalSupply',
      stateMutability: 'view',
      inputs: [],
      outputs: [{ name: 'totalSupply', type: 'uint256' }],
    },
  },
  {
    label: 'balanceOf(address)',
    signature: 'balanceOf(address)',
    methodName: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address', placeholder: '0x...' }],
    outputs: numberResult('balance'),
    abi: {
      type: 'function',
      name: 'balanceOf',
      stateMutability: 'view',
      inputs: [{ name: 'account', type: 'address' }],
      outputs: [{ name: 'balance', type: 'uint256' }],
    },
  },
  {
    label: 'transfer(address,uint256)',
    signature: 'transfer(address,uint256)',
    methodName: 'transfer',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address', placeholder: '0x...' },
      { name: 'amount', type: 'uint256', placeholder: '1000000000000000000' },
    ],
    outputs: boolResult('success'),
    abi: {
      type: 'function',
      name: 'transfer',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'to', type: 'address' },
        { name: 'amount', type: 'uint256' },
      ],
      outputs: [{ name: 'success', type: 'bool' }],
    },
  },
  {
    label: 'approve(address,uint256)',
    signature: 'approve(address,uint256)',
    methodName: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address', placeholder: '0x...' },
      { name: 'amount', type: 'uint256', placeholder: '1000000000000000000' },
    ],
    outputs: boolResult('success'),
    abi: {
      type: 'function',
      name: 'approve',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'spender', type: 'address' },
        { name: 'amount', type: 'uint256' },
      ],
      outputs: [{ name: 'success', type: 'bool' }],
    },
  },
  {
    label: 'allowance(address,address)',
    signature: 'allowance(address,address)',
    methodName: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address', placeholder: '0x...' },
      { name: 'spender', type: 'address', placeholder: '0x...' },
    ],
    outputs: numberResult('remaining'),
    abi: {
      type: 'function',
      name: 'allowance',
      stateMutability: 'view',
      inputs: [
        { name: 'owner', type: 'address' },
        { name: 'spender', type: 'address' },
      ],
      outputs: [{ name: 'remaining', type: 'uint256' }],
    },
  },
  {
    label: 'transferFrom(address,address,uint256)',
    signature: 'transferFrom(address,address,uint256)',
    methodName: 'transferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address', placeholder: '0x...' },
      { name: 'to', type: 'address', placeholder: '0x...' },
      { name: 'amount', type: 'uint256', placeholder: '1' },
    ],
    outputs: boolResult('success'),
    abi: {
      type: 'function',
      name: 'transferFrom',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'from', type: 'address' },
        { name: 'to', type: 'address' },
        { name: 'amount', type: 'uint256' },
      ],
      outputs: [{ name: 'success', type: 'bool' }],
    },
  },
];

export const erc721Functions: AbiFunctionConfig[] = [
  {
    label: 'balanceOf(address)',
    signature: 'balanceOf(address)',
    methodName: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'owner', type: 'address', placeholder: '0x...' }],
    outputs: numberResult('balance'),
    abi: {
      type: 'function',
      name: 'balanceOf',
      stateMutability: 'view',
      inputs: [{ name: 'owner', type: 'address' }],
      outputs: [{ name: 'balance', type: 'uint256' }],
    },
  },
  {
    label: 'ownerOf(uint256)',
    signature: 'ownerOf(uint256)',
    methodName: 'ownerOf',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256', placeholder: '1' }],
    outputs: addressResult('owner'),
    abi: {
      type: 'function',
      name: 'ownerOf',
      stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }],
      outputs: [{ name: 'owner', type: 'address' }],
    },
  },
  {
    label: 'approve(address,uint256)',
    signature: 'approve(address,uint256)',
    methodName: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address', placeholder: '0x...' },
      { name: 'tokenId', type: 'uint256', placeholder: '1' },
    ],
    outputs: [],
    abi: {
      type: 'function',
      name: 'approve',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'to', type: 'address' },
        { name: 'tokenId', type: 'uint256' },
      ],
      outputs: [],
    },
  },
  {
    label: 'getApproved(uint256)',
    signature: 'getApproved(uint256)',
    methodName: 'getApproved',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256', placeholder: '1' }],
    outputs: addressResult('operator'),
    abi: {
      type: 'function',
      name: 'getApproved',
      stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }],
      outputs: [{ name: 'operator', type: 'address' }],
    },
  },
  {
    label: 'setApprovalForAll(address,bool)',
    signature: 'setApprovalForAll(address,bool)',
    methodName: 'setApprovalForAll',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'operator', type: 'address', placeholder: '0x...' },
      { name: 'approved', type: 'bool' },
    ],
    outputs: [],
    abi: {
      type: 'function',
      name: 'setApprovalForAll',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'operator', type: 'address' },
        { name: 'approved', type: 'bool' },
      ],
      outputs: [],
    },
  },
  {
    label: 'isApprovedForAll(address,address)',
    signature: 'isApprovedForAll(address,address)',
    methodName: 'isApprovedForAll',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address', placeholder: '0x...' },
      { name: 'operator', type: 'address', placeholder: '0x...' },
    ],
    outputs: boolResult('approved'),
    abi: {
      type: 'function',
      name: 'isApprovedForAll',
      stateMutability: 'view',
      inputs: [
        { name: 'owner', type: 'address' },
        { name: 'operator', type: 'address' },
      ],
      outputs: [{ name: 'approved', type: 'bool' }],
    },
  },
  {
    label: 'transferFrom(address,address,uint256)',
    signature: 'transferFrom(address,address,uint256)',
    methodName: 'transferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address', placeholder: '0x...' },
      { name: 'to', type: 'address', placeholder: '0x...' },
      { name: 'tokenId', type: 'uint256', placeholder: '1' },
    ],
    outputs: [],
    abi: {
      type: 'function',
      name: 'transferFrom',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'from', type: 'address' },
        { name: 'to', type: 'address' },
        { name: 'tokenId', type: 'uint256' },
      ],
      outputs: [],
    },
  },
  {
    label: 'safeTransferFrom(address,address,uint256)',
    signature: 'safeTransferFrom(address,address,uint256)',
    methodName: 'safeTransferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address', placeholder: '0x...' },
      { name: 'to', type: 'address', placeholder: '0x...' },
      { name: 'tokenId', type: 'uint256', placeholder: '1' },
    ],
    outputs: [],
    abi: {
      type: 'function',
      name: 'safeTransferFrom',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'from', type: 'address' },
        { name: 'to', type: 'address' },
        { name: 'tokenId', type: 'uint256' },
      ],
      outputs: [],
    },
  },
  {
    label: 'tokenURI(uint256)',
    signature: 'tokenURI(uint256)',
    methodName: 'tokenURI',
    stateMutability: 'view',
    inputs: [{ name: 'tokenId', type: 'uint256', placeholder: '1' }],
    outputs: textResult('uri'),
    abi: {
      type: 'function',
      name: 'tokenURI',
      stateMutability: 'view',
      inputs: [{ name: 'tokenId', type: 'uint256' }],
      outputs: [{ name: 'uri', type: 'string' }],
    },
  },
];

export const erc1155Functions: AbiFunctionConfig[] = [
  {
    label: 'balanceOf(address,uint256)',
    signature: 'balanceOf(address,uint256)',
    methodName: 'balanceOf',
    stateMutability: 'view',
    inputs: [
      { name: 'account', type: 'address', placeholder: '0x...' },
      { name: 'id', type: 'uint256', placeholder: '1' },
    ],
    outputs: numberResult('balance'),
    abi: {
      type: 'function',
      name: 'balanceOf',
      stateMutability: 'view',
      inputs: [
        { name: 'account', type: 'address' },
        { name: 'id', type: 'uint256' },
      ],
      outputs: [{ name: 'balance', type: 'uint256' }],
    },
  },
  {
    label: 'balanceOfBatch(address[],uint256[])',
    signature: 'balanceOfBatch(address[],uint256[])',
    methodName: 'balanceOfBatch',
    stateMutability: 'view',
    inputs: [
      { name: 'accounts', type: 'address[]', placeholder: '["0x...","0x..."]' },
      { name: 'ids', type: 'uint256[]', placeholder: '[1,2]' },
    ],
    outputs: [{ name: 'balances', type: 'uint256[]' }],
    abi: {
      type: 'function',
      name: 'balanceOfBatch',
      stateMutability: 'view',
      inputs: [
        { name: 'accounts', type: 'address[]' },
        { name: 'ids', type: 'uint256[]' },
      ],
      outputs: [{ name: 'balances', type: 'uint256[]' }],
    },
  },
  {
    label: 'setApprovalForAll(address,bool)',
    signature: 'setApprovalForAll(address,bool)',
    methodName: 'setApprovalForAll',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'operator', type: 'address', placeholder: '0x...' },
      { name: 'approved', type: 'bool' },
    ],
    outputs: [],
    abi: {
      type: 'function',
      name: 'setApprovalForAll',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'operator', type: 'address' },
        { name: 'approved', type: 'bool' },
      ],
      outputs: [],
    },
  },
  {
    label: 'isApprovedForAll(address,address)',
    signature: 'isApprovedForAll(address,address)',
    methodName: 'isApprovedForAll',
    stateMutability: 'view',
    inputs: [
      { name: 'account', type: 'address', placeholder: '0x...' },
      { name: 'operator', type: 'address', placeholder: '0x...' },
    ],
    outputs: boolResult('approved'),
    abi: {
      type: 'function',
      name: 'isApprovedForAll',
      stateMutability: 'view',
      inputs: [
        { name: 'account', type: 'address' },
        { name: 'operator', type: 'address' },
      ],
      outputs: [{ name: 'approved', type: 'bool' }],
    },
  },
  {
    label: 'safeTransferFrom(address,address,uint256,uint256,bytes)',
    signature: 'safeTransferFrom(address,address,uint256,uint256,bytes)',
    methodName: 'safeTransferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address', placeholder: '0x...' },
      { name: 'to', type: 'address', placeholder: '0x...' },
      { name: 'id', type: 'uint256', placeholder: '1' },
      { name: 'amount', type: 'uint256', placeholder: '1' },
      { name: 'data', type: 'bytes', placeholder: '0x' },
    ],
    outputs: [],
    abi: {
      type: 'function',
      name: 'safeTransferFrom',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'from', type: 'address' },
        { name: 'to', type: 'address' },
        { name: 'id', type: 'uint256' },
        { name: 'amount', type: 'uint256' },
        { name: 'data', type: 'bytes' },
      ],
      outputs: [],
    },
  },
  {
    label: 'safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)',
    signature: 'safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)',
    methodName: 'safeBatchTransferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'from', type: 'address', placeholder: '0x...' },
      { name: 'to', type: 'address', placeholder: '0x...' },
      { name: 'ids', type: 'uint256[]', placeholder: '[1,2]' },
      { name: 'amounts', type: 'uint256[]', placeholder: '[10,20]' },
      { name: 'data', type: 'bytes', placeholder: '0x' },
    ],
    outputs: [],
    abi: {
      type: 'function',
      name: 'safeBatchTransferFrom',
      stateMutability: 'nonpayable',
      inputs: [
        { name: 'from', type: 'address' },
        { name: 'to', type: 'address' },
        { name: 'ids', type: 'uint256[]' },
        { name: 'amounts', type: 'uint256[]' },
        { name: 'data', type: 'bytes' },
      ],
      outputs: [],
    },
  },
  {
    label: 'uri(uint256)',
    signature: 'uri(uint256)',
    methodName: 'uri',
    stateMutability: 'view',
    inputs: [{ name: 'id', type: 'uint256', placeholder: '1' }],
    outputs: textResult('uri'),
    abi: {
      type: 'function',
      name: 'uri',
      stateMutability: 'view',
      inputs: [{ name: 'id', type: 'uint256' }],
      outputs: [{ name: 'uri', type: 'string' }],
    },
  },
];
